-- Based on hammerspoon-config
-- Window management

-- Define window maximize toggler
local frameCache = {}
local logger = hs.logger.new("window")

function winResize(method)
   --[[
      method: one of "left", "right", "up", "down", "max",
      "hthird-0", "hthird-1", "hthird-2",
      "vthird-0", "vthird-1", "vthird-2"
   ]]
   local win = hs.window.focusedWindow()
   if not win then
      hs.alert.show("No focused window")
      return
   end
   local newWin

   local method_table = {
      ["left"] = hs.layout.left50,
      ["right"] = hs.layout.right50,
      ["up"] = {0, 0, 1, 0.5},
      ["down"] = {0, 0.5, 1, 0.5},
      ["max"] = hs.layout.maximized,
      ["hthird-0"] = {0, 0, 1/3, 1},
      ["hthird-1"] = {1/3, 0, 1/3, 1},
      ["hthird-2"] = {2/3, 0, 1/3, 1},
      ["vthird-0"] = {0, 0, 1, 1/3},
      ["vthird-1"] = {0, 1/3, 1, 1/3},
      ["vthird-2"] = {0, 2/3, 1, 1/3},
      ["left-up"] = {0, 0, 0.5, 0.5},
      ["left-down"] = {0, 0.5, 0.5, 0.5},
      ["right-up"] = {0.5, 0, 0.5, 0.5},
      ["right-down"] = {0.5, 0.5, 0.5, 0.5},
      -- The followings are generated by Copilot
      -- Check and use it if I need
      -- ["left-max"] = {0, 0, 0.5, 1},
      -- ["right-max"] = {0.5, 0, 0.5, 1},
      -- ["up-max"] = {0, 0, 1, 0.5},
      -- ["down-max"] = {0, 0.5, 1, 0.5},
      -- ["left-third"] = {0, 0, 1/3, 1},
      -- ["right-third"] = {2/3, 0, 1/3, 1},
      -- ["mid-third"] = {1/3, 0, 1/3, 1},
      -- ["left-two-third"] = {0, 0, 2/3, 1},
      -- ["right-two-third"] = {1/3, 0, 2/3, 1},
      -- ["mid-two-third"] = {1/6, 0, 2/3, 1},
      -- ["left-two-third-up"] = {0, 0, 2/3, 1/2},
      -- ["left-two-third-down"] = {0, 1/2, 2/3, 1/2},
      -- ["right-two-third-up"] = {1/3, 0, 2/3, 1/2},
      -- ["right-two-third-down"] = {1/3, 1/2, 2/3, 1/2},
      -- ["mid-two-third-up"] = {1/6, 0, 2/3, 1/2},
      -- ["mid-two-third-down"] = {1/6, 1/2, 2/3, 1/2},
      -- ["left-two-third-max"] = {0, 0, 2/3, 1},
      -- ["right-two-third-max"] = {1/3, 0
   }
   newWin = method_table[method]

   win:move(newWin)
end

function winCenter()
   local win = hs.window.focusedWindow()
   win:centerOnScreen()
end

hs.hotkey.bind({"ctrl", "alt"}, "left", hs.fnutils.partial(winResize, "left"))
hs.hotkey.bind({"ctrl", "alt"}, "right", hs.fnutils.partial(winResize, "right"))
hs.hotkey.bind({"ctrl", "alt"}, "up", hs.fnutils.partial(winResize, "up"))
hs.hotkey.bind({"ctrl", "alt"}, "down", hs.fnutils.partial(winResize, "down"))
hs.hotkey.bind({"ctrl", "alt"}, "return", hs.fnutils.partial(winResize, "max"))
hs.hotkey.bind({"ctrl", "alt"}, "C", winCenter)
hs.hotkey.bind({"ctrl", "alt"}, "-", hs.fnutils.partial(winResize, "left-up"))
hs.hotkey.bind({"ctrl", "alt"}, "=", hs.fnutils.partial(winResize, "right-up"))
hs.hotkey.bind({"ctrl", "alt"}, "[", hs.fnutils.partial(winResize, "left-down"))
hs.hotkey.bind({"ctrl", "alt"}, "]", hs.fnutils.partial(winResize, "right-down"))
