name: Update .emacs.d

on:
  push:
    paths:
      - '.emacs.d/**'

jobs:
  update-emacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout parent repository
        uses: actions/checkout@v2

      - name: Checkout .emacs.d submodule
        run: git submodule update --init --recursive

      - name: Commit and push changes
        run: |
          git add .emacs.d
          git commit -m "Update .emacs.d submodule"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
