name: Update Submodules

on: workflow_dispatch

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dotfiles
        uses: actions/checkout@v4

      - name: Checkout submodules
        run: git submodule update --init --remote

      - name: Commit and push changes
        run: |
          git submodule update --init --remote
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Update submodules" || exit 0
          git push || exit 0
